services:
  - type: web
    name: fake-document-screening-api
    runtime: python
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: apt-get install -y tesseract-ocr && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
